### ISSUE TITLE
Authorization

### ISSUE THREAD

**Issue by YousefED** [pubkey/client-side-databases#8]
Awesome research @pubkey! I've been researching various offline-first models as well so this repo is particularly interesting. 

I'm wondering what your experience around Authorization with these different databases is - I think this is often where these databases get more complicated. I.e.; a chat-app would not be of much use if user A can modify or delete messages of user B (in a conversation between A and B).

I'm not sure whether creating an issue was the right approach for this, but imo it would be cool to document your experience with this in the repo as well, or make it part of the feature table

**Comment by pubkey** [comment]
Closing this. PR is welcomed.
